SELECT dblink_connect('argus_conn', 'host=localhost port=5432 dbname=argus user=argus');
SET session_replication_role = 'replica';

INSERT INTO storage_volumes SELECT * FROM dblink('argus_conn', 'SELECT id, asset_id, volume_name, total_gb, used_gb, filesystem, raid_level, status, created_at, updated_at FROM storage_volumes') AS t(id INT, asset_id INT, volume_name VARCHAR, total_gb NUMERIC, used_gb NUMERIC, filesystem VARCHAR, raid_level VARCHAR, status VARCHAR, created_at TIMESTAMPTZ, updated_at TIMESTAMPTZ);
INSERT INTO storage_connections SELECT * FROM dblink('argus_conn', 'SELECT id, storage_asset_id, server_asset_id, connection_type, mount_point, is_active, created_at FROM storage_connections') AS t(id INT, storage_asset_id INT, server_asset_id INT, connection_type VARCHAR, mount_point VARCHAR, is_active BOOLEAN, created_at TIMESTAMPTZ);
INSERT INTO storage_volume_history SELECT * FROM dblink('argus_conn', 'SELECT id, asset_id, volume_name, total_gb, used_gb, recorded_at FROM storage_volume_history') AS t(id INT, asset_id INT, volume_name VARCHAR, total_gb NUMERIC, used_gb NUMERIC, recorded_at TIMESTAMPTZ);
INSERT INTO virtual_hosts SELECT * FROM dblink('argus_conn', 'SELECT id, asset_id, platform, hostname, ip_address, version, cpu_total, mem_total_gb, vm_count, status, last_seen, created_at, updated_at FROM virtual_hosts') AS t(id INT, asset_id INT, platform VARCHAR, hostname VARCHAR, ip_address INET, version VARCHAR, cpu_total SMALLINT, mem_total_gb NUMERIC, vm_count INT, status VARCHAR, last_seen TIMESTAMPTZ, created_at TIMESTAMPTZ, updated_at TIMESTAMPTZ);
INSERT INTO service_checks SELECT * FROM dblink('argus_conn', 'SELECT id, asset_id, name, type, target, interval_s, timeout_s, expected_code, expected_body, is_active, created_at FROM service_checks') AS t(id INT, asset_id INT, name VARCHAR, type VARCHAR, target VARCHAR, interval_s INT, timeout_s INT, expected_code SMALLINT, expected_body VARCHAR, is_active BOOLEAN, created_at TIMESTAMPTZ);
INSERT INTO ssl_certificates SELECT * FROM dblink('argus_conn', 'SELECT id, asset_id, hostname, port, subject, issuer, not_before, not_after, last_checked, status, warn_days FROM ssl_certificates') AS t(id INT, asset_id INT, hostname VARCHAR, port SMALLINT, subject VARCHAR, issuer VARCHAR, not_before TIMESTAMPTZ, not_after TIMESTAMPTZ, last_checked TIMESTAMPTZ, status VARCHAR, warn_days INT);
INSERT INTO ssl_domains SELECT * FROM dblink('argus_conn', 'SELECT id, domain, domain_type, issuer, issued_at, expires_at, auto_renew, contact_name, contact_email, notes, is_active, created_at FROM ssl_domains') AS t(id INT, domain VARCHAR, domain_type VARCHAR, issuer VARCHAR, issued_at TIMESTAMPTZ, expires_at TIMESTAMPTZ, auto_renew BOOLEAN, contact_name VARCHAR, contact_email VARCHAR, notes TEXT, is_active BOOLEAN, created_at TIMESTAMPTZ);
INSERT INTO asset_changes SELECT * FROM dblink('argus_conn', 'SELECT id, asset_id, asset_name, field_name, old_value, new_value, changed_by, note, changed_at FROM asset_changes') AS t(id INT, asset_id INT, asset_name VARCHAR, field_name VARCHAR, old_value TEXT, new_value TEXT, changed_by VARCHAR, note TEXT, changed_at TIMESTAMPTZ);
INSERT INTO config_changes SELECT * FROM dblink('argus_conn', 'SELECT id, asset_id, detected_at, change_type, summary, raw_log, source FROM config_changes') AS t(id BIGINT, asset_id INT, detected_at TIMESTAMPTZ, change_type VARCHAR, summary VARCHAR, raw_log TEXT, source VARCHAR);
INSERT INTO ip_subnets SELECT * FROM dblink('argus_conn', 'SELECT id, subnet, name, vlan, location, description, is_active, created_at FROM ip_subnets') AS t(id INT, subnet CIDR, name VARCHAR, vlan SMALLINT, location VARCHAR, description TEXT, is_active BOOLEAN, created_at TIMESTAMPTZ);
INSERT INTO racks SELECT * FROM dblink('argus_conn', 'SELECT id, name, location, row_no, total_u, description, created_at FROM racks') AS t(id INT, name VARCHAR, location VARCHAR, row_no VARCHAR, total_u INT, description TEXT, created_at TIMESTAMPTZ);
INSERT INTO alert_rules SELECT * FROM dblink('argus_conn', 'SELECT id, name, asset_id, group_tag, asset_type_filter, metric, operator, threshold, duration_s, severity, notify_channels, is_active, created_at FROM alert_rules') AS t(id INT, name VARCHAR, asset_id INT, group_tag VARCHAR, asset_type_filter VARCHAR, metric VARCHAR, operator VARCHAR, threshold FLOAT, duration_s INT, severity VARCHAR, notify_channels TEXT[], is_active BOOLEAN, created_at TIMESTAMPTZ);
INSERT INTO escalation_policies SELECT * FROM dblink('argus_conn', 'SELECT id, name, asset_id, group_tag, steps, is_active, created_at FROM escalation_policies') AS t(id INT, name VARCHAR, asset_id INT, group_tag VARCHAR, steps JSONB, is_active BOOLEAN, created_at TIMESTAMPTZ);
INSERT INTO incidents SELECT * FROM dblink('argus_conn', 'SELECT id, title, severity, status, asset_ids, alert_ids, assigned_to, root_cause, resolution, opened_at, resolved_at FROM incidents') AS t(id INT, title VARCHAR, severity VARCHAR, status VARCHAR, asset_ids INT[], alert_ids BIGINT[], assigned_to INT, root_cause TEXT, resolution TEXT, opened_at TIMESTAMPTZ, resolved_at TIMESTAMPTZ);
INSERT INTO llm_providers SELECT * FROM dblink('argus_conn', 'SELECT id, name, provider_type, model, endpoint_url, api_key, extra_config, is_active, is_default, created_at FROM llm_providers') AS t(id INT, name VARCHAR, provider_type VARCHAR, model VARCHAR, endpoint_url VARCHAR, api_key TEXT, extra_config JSONB, is_active BOOLEAN, is_default BOOLEAN, created_at TIMESTAMPTZ);
INSERT INTO llm_predictions SELECT * FROM dblink('argus_conn', 'SELECT id, asset_id, predicted_at, issue_type, severity, confidence, summary, raw_response, alert_sent FROM llm_predictions') AS t(id INT, asset_id INT, predicted_at TIMESTAMPTZ, issue_type VARCHAR, severity VARCHAR, confidence FLOAT, summary TEXT, raw_response TEXT, alert_sent BOOLEAN);
INSERT INTO report_definitions SELECT * FROM dblink('argus_conn', 'SELECT id, name, type, schedule, asset_ids, format, recipients, is_active, last_run_at, created_at FROM report_definitions') AS t(id INT, name VARCHAR, type VARCHAR, schedule VARCHAR, asset_ids INT[], format VARCHAR, recipients TEXT[], is_active BOOLEAN, last_run_at TIMESTAMPTZ, created_at TIMESTAMPTZ);
INSERT INTO custom_dashboards SELECT * FROM dblink('argus_conn', 'SELECT id, user_id, name, layout, is_default, created_at, updated_at FROM custom_dashboards') AS t(id INT, user_id INT, name VARCHAR, layout JSONB, is_default BOOLEAN, created_at TIMESTAMPTZ, updated_at TIMESTAMPTZ);

-- child tables
INSERT INTO virtual_machines SELECT * FROM dblink('argus_conn', 'SELECT id, host_id, asset_id, vm_name, vm_uuid, guest_os, cpu_count, mem_mb, disk_gb, power_state, ip_address, tools_status, cpu_usage_pct, mem_usage_pct, created_at, updated_at FROM virtual_machines') AS t(id INT, host_id INT, asset_id INT, vm_name VARCHAR, vm_uuid VARCHAR, guest_os VARCHAR, cpu_count SMALLINT, mem_mb INT, disk_gb NUMERIC, power_state VARCHAR, ip_address INET, tools_status VARCHAR, cpu_usage_pct FLOAT, mem_usage_pct FLOAT, created_at TIMESTAMPTZ, updated_at TIMESTAMPTZ);
INSERT INTO service_check_results SELECT * FROM dblink('argus_conn', 'SELECT check_id, checked_at, status, response_ms, message FROM service_check_results') AS t(check_id INT, checked_at TIMESTAMPTZ, status VARCHAR, response_ms INT, message VARCHAR);
INSERT INTO ip_allocations SELECT * FROM dblink('argus_conn', 'SELECT id, subnet_id, ip_address, asset_id, hostname, purpose, status, notes, updated_at FROM ip_allocations') AS t(id INT, subnet_id INT, ip_address INET, asset_id INT, hostname VARCHAR, purpose VARCHAR, status VARCHAR, notes TEXT, updated_at TIMESTAMPTZ);
INSERT INTO rack_units SELECT * FROM dblink('argus_conn', 'SELECT id, rack_id, asset_id, start_u, size_u, label, unit_type, created_at FROM rack_units') AS t(id INT, rack_id INT, asset_id INT, start_u INT, size_u INT, label VARCHAR, unit_type VARCHAR, created_at TIMESTAMPTZ);
INSERT INTO alerts SELECT * FROM dblink('argus_conn', 'SELECT id, rule_id, asset_id, severity, title, message, source, status, fired_at, resolved_at, acked_at, acked_by FROM alerts') AS t(id BIGINT, rule_id INT, asset_id INT, severity VARCHAR, title VARCHAR, message TEXT, source VARCHAR, status VARCHAR, fired_at TIMESTAMPTZ, resolved_at TIMESTAMPTZ, acked_at TIMESTAMPTZ, acked_by INT);
INSERT INTO llm_feature_assignments SELECT * FROM dblink('argus_conn', 'SELECT feature, provider_id, fallback_id FROM llm_feature_assignments') AS t(feature VARCHAR, provider_id INT, fallback_id INT);
INSERT INTO incident_timeline SELECT * FROM dblink('argus_conn', 'SELECT id, incident_id, user_id, event_type, content, occurred_at FROM incident_timeline') AS t(id INT, incident_id INT, user_id INT, event_type VARCHAR, content TEXT, occurred_at TIMESTAMPTZ);
INSERT INTO report_history SELECT * FROM dblink('argus_conn', 'SELECT id, def_id, generated_at, period_start, period_end, file_path, status FROM report_history') AS t(id INT, def_id INT, generated_at TIMESTAMPTZ, period_start TIMESTAMPTZ, period_end TIMESTAMPTZ, file_path VARCHAR, status VARCHAR);
INSERT INTO alert_notifications SELECT * FROM dblink('argus_conn', 'SELECT id, alert_id, channel, recipient, status, sent_at, error FROM alert_notifications') AS t(id BIGINT, alert_id BIGINT, channel VARCHAR, recipient VARCHAR, status VARCHAR, sent_at TIMESTAMPTZ, error TEXT);
INSERT INTO llm_call_logs SELECT * FROM dblink('argus_conn', 'SELECT id, provider_id, feature, model, prompt_tokens, completion_tokens, duration_ms, status, error_message, called_at FROM llm_call_logs') AS t(id BIGINT, provider_id INT, feature VARCHAR, model VARCHAR, prompt_tokens INT, completion_tokens INT, duration_ms INT, status VARCHAR, error_message TEXT, called_at TIMESTAMPTZ);

SET session_replication_role = 'origin';

-- Update admin branding
UPDATE users SET
  email = REPLACE(email, '@argus.local', '@digicap.local'),
  password_hash = crypt('digicap1234!', gen_salt('bf'))
WHERE username = 'admin' AND email LIKE '%@argus.local';

SELECT dblink_disconnect('argus_conn');
