-- Full migration: argus → digicap (fixed: skip non-existent tables)
SELECT dblink_connect('src', 'host=localhost port=5432 dbname=argus user=argus');
SET session_replication_role = 'replica';

-- TRUNCATE all
TRUNCATE users, organizations, system_settings, syslog_parse_patterns CASCADE;

-- 1단계: 독립 테이블
INSERT INTO users SELECT * FROM dblink('src', 'SELECT id, username, email, password_hash, role, is_active, failed_attempts, locked_until, last_login, created_at FROM users') AS t(id INT, username VARCHAR, email VARCHAR, password_hash TEXT, role VARCHAR, is_active BOOLEAN, failed_attempts INT, locked_until TIMESTAMPTZ, last_login TIMESTAMPTZ, created_at TIMESTAMPTZ);
INSERT INTO organizations SELECT * FROM dblink('src', 'SELECT id, name, parent_id, org_type, manager_name, contact, sort_order, is_active, created_at FROM organizations') AS t(id INT, name VARCHAR, parent_id INT, org_type VARCHAR, manager_name VARCHAR, contact VARCHAR, sort_order INT, is_active BOOLEAN, created_at TIMESTAMPTZ);
INSERT INTO system_settings SELECT * FROM dblink('src', 'SELECT key, value, description, updated_at FROM system_settings') AS t(key VARCHAR, value TEXT, description VARCHAR, updated_at TIMESTAMPTZ) ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value, updated_at = EXCLUDED.updated_at;
INSERT INTO syslog_parse_patterns SELECT * FROM dblink('src', 'SELECT id, name, vendor, event_type, pattern, wwn_group, mac_group, port_group, priority, is_active FROM syslog_parse_patterns') AS t(id INT, name VARCHAR, vendor VARCHAR, event_type VARCHAR, pattern TEXT, wwn_group INT, mac_group INT, port_group INT, priority INT, is_active BOOLEAN) ON CONFLICT (id) DO NOTHING;

-- 2단계: assets
INSERT INTO assets SELECT * FROM dblink('src', 'SELECT id, name, hostname, ip_address, type, os, os_version, arch, location, group_tag, manufacturer, model, serial_number, bmc_ip, bmc_type, bmc_enabled, monitoring_enabled, agent_version, agent_url, node_type, manager, user_name, user_team, org_id, registration_source, status, lifecycle_status, decommission_at, decommission_note, last_seen, introduced_at, is_active, created_at, updated_at FROM assets') AS t(id INT, name VARCHAR, hostname VARCHAR, ip_address INET, type VARCHAR, os VARCHAR, os_version VARCHAR, arch VARCHAR, location VARCHAR, group_tag VARCHAR, manufacturer VARCHAR, model VARCHAR, serial_number VARCHAR, bmc_ip INET, bmc_type VARCHAR, bmc_enabled BOOLEAN, monitoring_enabled BOOLEAN, agent_version VARCHAR, agent_url VARCHAR, node_type VARCHAR, manager VARCHAR, user_name VARCHAR, user_team VARCHAR, org_id INT, registration_source VARCHAR, status VARCHAR, lifecycle_status VARCHAR, decommission_at DATE, decommission_note TEXT, last_seen TIMESTAMPTZ, introduced_at DATE, is_active BOOLEAN, created_at TIMESTAMPTZ, updated_at TIMESTAMPTZ);
INSERT INTO audit_logs SELECT * FROM dblink('src', 'SELECT id, user_id, action, target_type, target_id, detail, ip_address, occurred_at FROM audit_logs') AS t(id BIGINT, user_id INT, action VARCHAR, target_type VARCHAR, target_id INT, detail JSONB, ip_address INET, occurred_at TIMESTAMPTZ);

-- 3단계: assets 참조
INSERT INTO maintenance_contracts SELECT * FROM dblink('src', 'SELECT id, asset_id, has_contract, contract_type, vendor, contract_start, contract_end, contact_name, contact_phone, contact_email, software_name, software_version, license_count, notes, is_active, updated_at FROM maintenance_contracts') AS t(id INT, asset_id INT, has_contract BOOLEAN, contract_type VARCHAR, vendor VARCHAR, contract_start DATE, contract_end DATE, contact_name VARCHAR, contact_phone VARCHAR, contact_email VARCHAR, software_name VARCHAR, software_version VARCHAR, license_count INT, notes TEXT, is_active BOOLEAN, updated_at TIMESTAMPTZ);
INSERT INTO software_installations SELECT * FROM dblink('src', 'SELECT id, contract_id, asset_id, installed_at, notes FROM software_installations') AS t(id INT, contract_id INT, asset_id INT, installed_at TIMESTAMPTZ, notes TEXT);
INSERT INTO bmc_credentials SELECT * FROM dblink('src', 'SELECT id, asset_id, username, password, updated_at FROM bmc_credentials') AS t(id INT, asset_id INT, username VARCHAR, password TEXT, updated_at TIMESTAMPTZ);
INSERT INTO agent_tokens SELECT * FROM dblink('src', 'SELECT id, asset_id, token, label, last_seen, revoked, created_at FROM agent_tokens') AS t(id INT, asset_id INT, token VARCHAR, label VARCHAR, last_seen TIMESTAMPTZ, revoked BOOLEAN, created_at TIMESTAMPTZ);
INSERT INTO agent_versions SELECT * FROM dblink('src', 'SELECT id, version, os, arch, file_path, checksum, release_notes, is_stable, released_at FROM agent_versions') AS t(id INT, version VARCHAR, os VARCHAR, arch VARCHAR, file_path VARCHAR, checksum VARCHAR, release_notes TEXT, is_stable BOOLEAN, released_at TIMESTAMPTZ);

-- 시계열 데이터
INSERT INTO metrics SELECT * FROM dblink('src', 'SELECT asset_id, collected_at, cpu_usage, mem_usage, mem_total_mb, mem_used_mb, disk_read_bps, disk_write_bps, disk_usage_pct, net_rx_bps, net_tx_bps, load_avg_1m, process_count FROM metrics') AS t(asset_id INT, collected_at TIMESTAMPTZ, cpu_usage FLOAT, mem_usage FLOAT, mem_total_mb BIGINT, mem_used_mb BIGINT, disk_read_bps BIGINT, disk_write_bps BIGINT, disk_usage_pct FLOAT, net_rx_bps BIGINT, net_tx_bps BIGINT, load_avg_1m FLOAT, process_count INT);
INSERT INTO metrics_5m SELECT * FROM dblink('src', 'SELECT asset_id, bucket, cpu_avg, cpu_max, mem_avg, mem_max, disk_read_avg, disk_write_avg, net_rx_avg, net_tx_avg, sample_count FROM metrics_5m') AS t(asset_id INT, bucket TIMESTAMPTZ, cpu_avg FLOAT, cpu_max FLOAT, mem_avg FLOAT, mem_max FLOAT, disk_read_avg BIGINT, disk_write_avg BIGINT, net_rx_avg BIGINT, net_tx_avg BIGINT, sample_count INT);
INSERT INTO metrics_1h SELECT * FROM dblink('src', 'SELECT asset_id, bucket, cpu_avg, cpu_max, mem_avg, mem_max, disk_read_avg, disk_write_avg, net_rx_avg, net_tx_avg, sample_count FROM metrics_1h') AS t(asset_id INT, bucket TIMESTAMPTZ, cpu_avg FLOAT, cpu_max FLOAT, mem_avg FLOAT, mem_max FLOAT, disk_read_avg BIGINT, disk_write_avg BIGINT, net_rx_avg BIGINT, net_tx_avg BIGINT, sample_count INT);
INSERT INTO disk_metrics SELECT * FROM dblink('src', 'SELECT id, asset_id, mount_point, device, filesystem, total_gb, used_gb, collected_at FROM disk_metrics') AS t(id BIGINT, asset_id INT, mount_point VARCHAR, device VARCHAR, filesystem VARCHAR, total_gb NUMERIC, used_gb NUMERIC, collected_at TIMESTAMPTZ);
INSERT INTO bmc_metrics SELECT * FROM dblink('src', 'SELECT asset_id, collected_at, power_watts, psu1_status, psu2_status, cpu1_temp_c, cpu2_temp_c, inlet_temp_c, outlet_temp_c, fan_speeds, overall_health FROM bmc_metrics') AS t(asset_id INT, collected_at TIMESTAMPTZ, power_watts INT, psu1_status VARCHAR, psu2_status VARCHAR, cpu1_temp_c SMALLINT, cpu2_temp_c SMALLINT, inlet_temp_c SMALLINT, outlet_temp_c SMALLINT, fan_speeds JSONB, overall_health VARCHAR);
INSERT INTO hw_inventory SELECT * FROM dblink('src', 'SELECT id, asset_id, bios_version, bmc_version, cpu_model, cpu_count, cpu_cores, mem_total_gb, mem_slots, disks, nics, collected_at FROM hw_inventory') AS t(id INT, asset_id INT, bios_version VARCHAR, bmc_version VARCHAR, cpu_model VARCHAR, cpu_count SMALLINT, cpu_cores SMALLINT, mem_total_gb INT, mem_slots JSONB, disks JSONB, nics JSONB, collected_at TIMESTAMPTZ);
INSERT INTO hw_health SELECT * FROM dblink('src', 'SELECT id, asset_id, component, name, status, message, checked_at FROM hw_health') AS t(id INT, asset_id INT, component VARCHAR, name VARCHAR, status VARCHAR, message VARCHAR, checked_at TIMESTAMPTZ);
INSERT INTO bmc_sel SELECT * FROM dblink('src', 'SELECT id, asset_id, event_id, occurred_at, severity, component, message, raw FROM bmc_sel') AS t(id BIGINT, asset_id INT, event_id VARCHAR, occurred_at TIMESTAMPTZ, severity VARCHAR, component VARCHAR, message TEXT, raw JSONB);
INSERT INTO disk_smart SELECT * FROM dblink('src', 'SELECT id, asset_id, device, model, serial, collected_at, health_status, temperature_c, reallocated_sectors, pending_sectors, uncorrectable, power_on_hours, raw FROM disk_smart') AS t(id INT, asset_id INT, device VARCHAR, model VARCHAR, serial VARCHAR, collected_at TIMESTAMPTZ, health_status VARCHAR, temperature_c SMALLINT, reallocated_sectors INT, pending_sectors INT, uncorrectable INT, power_on_hours INT, raw JSONB);
INSERT INTO syslog_entries SELECT * FROM dblink('src', 'SELECT id, asset_id, received_at, severity, facility, hostname, program, message, raw, event_type, parsed_data FROM syslog_entries') AS t(id BIGINT, asset_id INT, received_at TIMESTAMPTZ, severity SMALLINT, facility SMALLINT, hostname VARCHAR, program VARCHAR, message TEXT, raw TEXT, event_type VARCHAR, parsed_data JSONB);
INSERT INTO server_logs SELECT * FROM dblink('src', 'SELECT id, asset_id, collected_at, level, source, message FROM server_logs') AS t(id BIGINT, asset_id INT, collected_at TIMESTAMPTZ, level VARCHAR, source VARCHAR, message TEXT);
INSERT INTO network_ports SELECT * FROM dblink('src', 'SELECT id, asset_id, port_name, link_status, speed_mbps, if_index, duplex, vlan_id, description, last_changed, updated_at FROM network_ports') AS t(id INT, asset_id INT, port_name VARCHAR, link_status VARCHAR, speed_mbps INT, if_index SMALLINT, duplex VARCHAR, vlan_id SMALLINT, description VARCHAR, last_changed TIMESTAMPTZ, updated_at TIMESTAMPTZ);
INSERT INTO mac_addresses SELECT * FROM dblink('src', 'SELECT id, asset_id, mac, interface, ip_address, first_seen, last_seen FROM mac_addresses') AS t(id INT, asset_id INT, mac MACADDR, interface VARCHAR, ip_address INET, first_seen TIMESTAMPTZ, last_seen TIMESTAMPTZ);
INSERT INTO wwn_entries SELECT * FROM dblink('src', 'SELECT id, asset_id, wwn, wwn_type, port_name, first_seen, last_seen FROM wwn_entries') AS t(id INT, asset_id INT, wwn VARCHAR, wwn_type VARCHAR, port_name VARCHAR, first_seen TIMESTAMPTZ, last_seen TIMESTAMPTZ);
INSERT INTO topology_nodes SELECT * FROM dblink('src', 'SELECT id, asset_id, layer, node_type, label, pos_x, pos_y, meta, updated_at FROM topology_nodes') AS t(id INT, asset_id INT, layer VARCHAR, node_type VARCHAR, label VARCHAR, pos_x FLOAT, pos_y FLOAT, meta JSONB, updated_at TIMESTAMPTZ);
INSERT INTO topology_edges SELECT * FROM dblink('src', 'SELECT id, layer, source_node, target_node, source_port, target_port, link_type, method, confidence, is_active, detected_at, updated_at FROM topology_edges') AS t(id INT, layer VARCHAR, source_node INT, target_node INT, source_port VARCHAR, target_port VARCHAR, link_type VARCHAR, method VARCHAR, confidence SMALLINT, is_active BOOLEAN, detected_at TIMESTAMPTZ, updated_at TIMESTAMPTZ);
-- device_mac_table, discovery_logs: argus에 없음 → 건너뜀
INSERT INTO storage_volumes SELECT * FROM dblink('src', 'SELECT id, asset_id, volume_name, total_gb, used_gb, filesystem, raid_level, status, created_at, updated_at FROM storage_volumes') AS t(id INT, asset_id INT, volume_name VARCHAR, total_gb NUMERIC, used_gb NUMERIC, filesystem VARCHAR, raid_level VARCHAR, status VARCHAR, created_at TIMESTAMPTZ, updated_at TIMESTAMPTZ);
INSERT INTO storage_connections SELECT * FROM dblink('src', 'SELECT id, storage_asset_id, server_asset_id, connection_type, mount_point, is_active, created_at FROM storage_connections') AS t(id INT, storage_asset_id INT, server_asset_id INT, connection_type VARCHAR, mount_point VARCHAR, is_active BOOLEAN, created_at TIMESTAMPTZ);
INSERT INTO storage_volume_history SELECT * FROM dblink('src', 'SELECT id, asset_id, volume_name, total_gb, used_gb, recorded_at FROM storage_volume_history') AS t(id INT, asset_id INT, volume_name VARCHAR, total_gb NUMERIC, used_gb NUMERIC, recorded_at TIMESTAMPTZ);
INSERT INTO virtual_hosts SELECT * FROM dblink('src', 'SELECT id, asset_id, platform, hostname, ip_address, version, cpu_total, mem_total_gb, vm_count, status, last_seen, created_at, updated_at FROM virtual_hosts') AS t(id INT, asset_id INT, platform VARCHAR, hostname VARCHAR, ip_address INET, version VARCHAR, cpu_total SMALLINT, mem_total_gb NUMERIC, vm_count INT, status VARCHAR, last_seen TIMESTAMPTZ, created_at TIMESTAMPTZ, updated_at TIMESTAMPTZ);
INSERT INTO service_checks SELECT * FROM dblink('src', 'SELECT id, asset_id, name, type, target, interval_s, timeout_s, expected_code, expected_body, is_active, created_at FROM service_checks') AS t(id INT, asset_id INT, name VARCHAR, type VARCHAR, target VARCHAR, interval_s INT, timeout_s INT, expected_code SMALLINT, expected_body VARCHAR, is_active BOOLEAN, created_at TIMESTAMPTZ);
INSERT INTO ssl_certificates SELECT * FROM dblink('src', 'SELECT id, asset_id, hostname, port, subject, issuer, not_before, not_after, last_checked, status, warn_days FROM ssl_certificates') AS t(id INT, asset_id INT, hostname VARCHAR, port SMALLINT, subject VARCHAR, issuer VARCHAR, not_before TIMESTAMPTZ, not_after TIMESTAMPTZ, last_checked TIMESTAMPTZ, status VARCHAR, warn_days INT);
INSERT INTO ssl_domains SELECT * FROM dblink('src', 'SELECT id, domain, domain_type, issuer, issued_at, expires_at, auto_renew, contact_name, contact_email, notes, is_active, created_at FROM ssl_domains') AS t(id INT, domain VARCHAR, domain_type VARCHAR, issuer VARCHAR, issued_at TIMESTAMPTZ, expires_at TIMESTAMPTZ, auto_renew BOOLEAN, contact_name VARCHAR, contact_email VARCHAR, notes TEXT, is_active BOOLEAN, created_at TIMESTAMPTZ);
INSERT INTO asset_changes SELECT * FROM dblink('src', 'SELECT id, asset_id, asset_name, field_name, old_value, new_value, changed_by, note, changed_at FROM asset_changes') AS t(id INT, asset_id INT, asset_name VARCHAR, field_name VARCHAR, old_value TEXT, new_value TEXT, changed_by VARCHAR, note TEXT, changed_at TIMESTAMPTZ);
INSERT INTO config_changes SELECT * FROM dblink('src', 'SELECT id, asset_id, detected_at, change_type, summary, raw_log, source FROM config_changes') AS t(id BIGINT, asset_id INT, detected_at TIMESTAMPTZ, change_type VARCHAR, summary VARCHAR, raw_log TEXT, source VARCHAR);
INSERT INTO ip_subnets SELECT * FROM dblink('src', 'SELECT id, subnet, name, vlan, location, description, is_active, created_at FROM ip_subnets') AS t(id INT, subnet CIDR, name VARCHAR, vlan SMALLINT, location VARCHAR, description TEXT, is_active BOOLEAN, created_at TIMESTAMPTZ);
INSERT INTO racks SELECT * FROM dblink('src', 'SELECT id, name, location, row_no, total_u, description, created_at FROM racks') AS t(id INT, name VARCHAR, location VARCHAR, row_no VARCHAR, total_u INT, description TEXT, created_at TIMESTAMPTZ);
INSERT INTO alert_rules SELECT * FROM dblink('src', 'SELECT id, name, asset_id, group_tag, asset_type_filter, metric, operator, threshold, duration_s, severity, notify_channels, is_active, created_at FROM alert_rules') AS t(id INT, name VARCHAR, asset_id INT, group_tag VARCHAR, asset_type_filter VARCHAR, metric VARCHAR, operator VARCHAR, threshold FLOAT, duration_s INT, severity VARCHAR, notify_channels TEXT[], is_active BOOLEAN, created_at TIMESTAMPTZ);
INSERT INTO escalation_policies SELECT * FROM dblink('src', 'SELECT id, name, asset_id, group_tag, steps, is_active, created_at FROM escalation_policies') AS t(id INT, name VARCHAR, asset_id INT, group_tag VARCHAR, steps JSONB, is_active BOOLEAN, created_at TIMESTAMPTZ);
INSERT INTO incidents SELECT * FROM dblink('src', 'SELECT id, title, severity, status, asset_ids, alert_ids, assigned_to, root_cause, resolution, opened_at, resolved_at FROM incidents') AS t(id INT, title VARCHAR, severity VARCHAR, status VARCHAR, asset_ids INT[], alert_ids BIGINT[], assigned_to INT, root_cause TEXT, resolution TEXT, opened_at TIMESTAMPTZ, resolved_at TIMESTAMPTZ);
INSERT INTO llm_providers SELECT * FROM dblink('src', 'SELECT id, name, provider_type, model, endpoint_url, api_key, extra_config, is_active, is_default, created_at FROM llm_providers') AS t(id INT, name VARCHAR, provider_type VARCHAR, model VARCHAR, endpoint_url VARCHAR, api_key TEXT, extra_config JSONB, is_active BOOLEAN, is_default BOOLEAN, created_at TIMESTAMPTZ);
INSERT INTO llm_predictions SELECT * FROM dblink('src', 'SELECT id, asset_id, predicted_at, issue_type, severity, confidence, summary, raw_response, alert_sent FROM llm_predictions') AS t(id INT, asset_id INT, predicted_at TIMESTAMPTZ, issue_type VARCHAR, severity VARCHAR, confidence FLOAT, summary TEXT, raw_response TEXT, alert_sent BOOLEAN);
INSERT INTO report_definitions SELECT * FROM dblink('src', 'SELECT id, name, type, schedule, asset_ids, format, recipients, is_active, last_run_at, created_at FROM report_definitions') AS t(id INT, name VARCHAR, type VARCHAR, schedule VARCHAR, asset_ids INT[], format VARCHAR, recipients TEXT[], is_active BOOLEAN, last_run_at TIMESTAMPTZ, created_at TIMESTAMPTZ);
INSERT INTO custom_dashboards SELECT * FROM dblink('src', 'SELECT id, user_id, name, layout, is_default, created_at, updated_at FROM custom_dashboards') AS t(id INT, user_id INT, name VARCHAR, layout JSONB, is_default BOOLEAN, created_at TIMESTAMPTZ, updated_at TIMESTAMPTZ);

-- 4단계: 자식 테이블
INSERT INTO virtual_machines SELECT * FROM dblink('src', 'SELECT id, host_id, asset_id, vm_name, vm_uuid, guest_os, cpu_count, mem_mb, disk_gb, power_state, ip_address, tools_status, cpu_usage_pct, mem_usage_pct, created_at, updated_at FROM virtual_machines') AS t(id INT, host_id INT, asset_id INT, vm_name VARCHAR, vm_uuid VARCHAR, guest_os VARCHAR, cpu_count SMALLINT, mem_mb INT, disk_gb NUMERIC, power_state VARCHAR, ip_address INET, tools_status VARCHAR, cpu_usage_pct FLOAT, mem_usage_pct FLOAT, created_at TIMESTAMPTZ, updated_at TIMESTAMPTZ);
INSERT INTO service_check_results SELECT * FROM dblink('src', 'SELECT check_id, checked_at, status, response_ms, message FROM service_check_results') AS t(check_id INT, checked_at TIMESTAMPTZ, status VARCHAR, response_ms INT, message VARCHAR);
INSERT INTO ip_allocations SELECT * FROM dblink('src', 'SELECT id, subnet_id, ip_address, asset_id, hostname, purpose, status, notes, updated_at FROM ip_allocations') AS t(id INT, subnet_id INT, ip_address INET, asset_id INT, hostname VARCHAR, purpose VARCHAR, status VARCHAR, notes TEXT, updated_at TIMESTAMPTZ);
INSERT INTO rack_units SELECT * FROM dblink('src', 'SELECT id, rack_id, asset_id, start_u, size_u, label, unit_type, created_at FROM rack_units') AS t(id INT, rack_id INT, asset_id INT, start_u INT, size_u INT, label VARCHAR, unit_type VARCHAR, created_at TIMESTAMPTZ);
INSERT INTO alerts SELECT * FROM dblink('src', 'SELECT id, rule_id, asset_id, severity, title, message, source, status, fired_at, resolved_at, acked_at, acked_by FROM alerts') AS t(id BIGINT, rule_id INT, asset_id INT, severity VARCHAR, title VARCHAR, message TEXT, source VARCHAR, status VARCHAR, fired_at TIMESTAMPTZ, resolved_at TIMESTAMPTZ, acked_at TIMESTAMPTZ, acked_by INT);
INSERT INTO llm_feature_assignments SELECT * FROM dblink('src', 'SELECT feature, provider_id, fallback_id FROM llm_feature_assignments') AS t(feature VARCHAR, provider_id INT, fallback_id INT) ON CONFLICT (feature) DO UPDATE SET provider_id = EXCLUDED.provider_id, fallback_id = EXCLUDED.fallback_id;
INSERT INTO incident_timeline SELECT * FROM dblink('src', 'SELECT id, incident_id, user_id, event_type, content, occurred_at FROM incident_timeline') AS t(id INT, incident_id INT, user_id INT, event_type VARCHAR, content TEXT, occurred_at TIMESTAMPTZ);
INSERT INTO report_history SELECT * FROM dblink('src', 'SELECT id, def_id, generated_at, period_start, period_end, file_path, status FROM report_history') AS t(id INT, def_id INT, generated_at TIMESTAMPTZ, period_start TIMESTAMPTZ, period_end TIMESTAMPTZ, file_path VARCHAR, status VARCHAR);
INSERT INTO alert_notifications SELECT * FROM dblink('src', 'SELECT id, alert_id, channel, recipient, status, sent_at, error FROM alert_notifications') AS t(id BIGINT, alert_id BIGINT, channel VARCHAR, recipient VARCHAR, status VARCHAR, sent_at TIMESTAMPTZ, error TEXT);
INSERT INTO llm_call_logs SELECT * FROM dblink('src', 'SELECT id, provider_id, feature, model, prompt_tokens, completion_tokens, duration_ms, status, error_message, called_at FROM llm_call_logs') AS t(id BIGINT, provider_id INT, feature VARCHAR, model VARCHAR, prompt_tokens INT, completion_tokens INT, duration_ms INT, status VARCHAR, error_message TEXT, called_at TIMESTAMPTZ);
INSERT INTO network_port_history SELECT * FROM dblink('src', 'SELECT id, asset_id, port_name, status, changed_at FROM network_port_history') AS t(id BIGINT, asset_id INT, port_name VARCHAR, status VARCHAR, changed_at TIMESTAMPTZ);

SET session_replication_role = 'origin';

-- admin 브랜딩 업데이트
UPDATE users SET email = REPLACE(email, '@argus.local', '@digicap.local'), password_hash = crypt('digicap1234!', gen_salt('bf')) WHERE username = 'admin' AND email LIKE '%@argus.local';

SELECT dblink_disconnect('src');
